
import { ArrowRight, FileText, Sparkles, BookOpen, CheckCircle, Zap, BarChart3, Diamond, Award, Search, List, Users, DollarSign, Briefcase, HelpCircle, GitCommit } from 'lucide-react';
import { ProductItem } from './ProductCategory';

export interface ProductCategory {
  id: string;
  title: string;
  description: string;
  bgColor: string;
  iconColor: string;
  icon: typeof FileText;
  products: ProductItem[];
}

// Product categories with their respective items
export const productCategories: ProductCategory[] = [
  {
    id: 'resume-tools',
    title: 'Resume & Profile Enhancement Tools',
    description: 'Enhance your professional presence with our cutting-edge tools designed to make you stand out to employers.',
    bgColor: 'bg-jobonboard-blue/5',
    iconColor: 'text-jobonboard-blue',
    icon: FileText,
    products: [
      {
        id: 'ai-resume-scanner',
        title: 'AI Resume Scanner',
        description: 'Get instant AI-powered feedback on your resume to improve your chances of landing interviews.',
        icon: Sparkles,
        cta: 'Scan My Resume',
        color: 'text-jobonboard-blue',
        bgColor: 'bg-jobonboard-blue/10',
        premium: false,
      },
      {
        id: 'resume-builder',
        title: 'Resume Builder',
        description: 'Create professional resumes with our easy-to-use builder featuring ATS-friendly templates.',
        icon: FileText,
        cta: 'Build My Resume',
        color: 'text-jobonboard-blue',
        bgColor: 'bg-jobonboard-blue/10',
        premium: false,
      },
      {
        id: 'linkedin-optimizer',
        title: 'LinkedIn Profile Optimizer',
        description: 'Improve your LinkedIn profile visibility with our optimization tool designed for recruiter searches.',
        icon: Users,
        cta: 'Optimize My Profile',
        color: 'text-jobonboard-blue',
        bgColor: 'bg-jobonboard-blue/10',
        premium: false,
      },
      {
        id: 'portfolio-builder',
        title: 'Portfolio Builder',
        description: 'Showcase your work with a professional online portfolio that highlights your skills and achievements.',
        icon: Briefcase,
        cta: 'Create Portfolio',
        color: 'text-jobonboard-blue',
        bgColor: 'bg-jobonboard-blue/10',
        premium: false,
      },
    ],
  },
  {
    id: 'job-search',
    title: 'Job Search & Career Assistance',
    description: 'Find the perfect job opportunities and get expert assistance in your career journey.',
    bgColor: 'bg-jobonboard-green/5',
    iconColor: 'text-jobonboard-green',
    icon: Search,
    products: [
      {
        id: 'job-tracker',
        title: 'Job Tracker Tool',
        description: 'Organize and track all your job applications in one place, never miss a follow-up again.',
        icon: List,
        cta: 'Start Tracking',
        color: 'text-jobonboard-green',
        bgColor: 'bg-jobonboard-green/10',
        premium: false,
      },
      {
        id: 'hidden-job-market',
        title: 'Hidden Job Market Access',
        description: 'Get exclusive access to unlisted job opportunities from our network of partner companies.',
        icon: HelpCircle,
        cta: 'Explore Hidden Jobs',
        color: 'text-jobonboard-green',
        bgColor: 'bg-jobonboard-green/10',
        premium: false,
      },
      {
        id: 'freelance-finder',
        title: 'Freelance & Side Gig Finder',
        description: 'Discover remote and freelance work opportunities to supplement your income or transition careers.',
        icon: GitCommit,
        cta: 'Find Gigs',
        color: 'text-jobonboard-green',
        bgColor: 'bg-jobonboard-green/10',
        premium: false,
      },
      {
        id: 'job-search-assistant',
        title: 'Personalized Job Search Assistant',
        description: 'Get customized guidance from experts to find the right job that aligns with your career goals.',
        icon: Users,
        cta: 'Get Assistance',
        color: 'text-jobonboard-green',
        bgColor: 'bg-jobonboard-green/10',
        premium: false,
      },
    ],
  },
  {
    id: 'interview-tools',
    title: 'Interview & Career Growth Tools',
    description: 'Prepare for interviews and develop the skills needed to grow in your career.',
    bgColor: 'bg-jobonboard-purple/5',
    iconColor: 'text-jobonboard-purple',
    icon: BookOpen,
    products: [
      {
        id: 'ai-mock-interview',
        title: 'AI Mock Interview Simulator',
        description: 'Practice interviews with our AI-powered simulator and get instant feedback to improve.',
        icon: Sparkles,
        cta: 'Start Practice',
        color: 'text-jobonboard-purple',
        bgColor: 'bg-jobonboard-purple/10',
        premium: false,
      },
      {
        id: 'interview-coaching',
        title: '1-on-1 Interview Coaching',
        description: 'Book personalized coaching sessions with industry professionals to prepare for specific roles.',
        icon: Users,
        cta: 'Book Session',
        color: 'text-jobonboard-purple',
        bgColor: 'bg-jobonboard-purple/10',
        premium: false,
      },
      {
        id: 'salary-negotiation',
        title: 'Salary Negotiation Toolkit',
        description: 'Learn effective strategies for negotiating better compensation packages with our comprehensive guide.',
        icon: DollarSign,
        cta: 'Access Toolkit',
        color: 'text-jobonboard-purple',
        bgColor: 'bg-jobonboard-purple/10',
        premium: false,
      },
      {
        id: 'soft-skills',
        title: 'Soft Skills Training Hub',
        description: 'Develop essential workplace skills with our courses on communication, leadership, and teamwork.',
        icon: Zap,
        cta: 'Explore Courses',
        color: 'text-jobonboard-purple',
        bgColor: 'bg-jobonboard-purple/10',
        premium: false,
      },
    ],
  },
  {
    id: 'premium-services',
    title: 'Exclusive Premium Offerings',
    description: 'Take your career to the next level with our exclusive premium services designed for ambitious professionals.',
    bgColor: 'bg-amber-50',
    iconColor: 'text-amber-500',
    icon: Diamond,
    products: [
      {
        id: 'interview-guarantee',
        title: 'Interview Guarantee Program',
        description: 'Our premium service that works with you until you successfully land interviews at your target companies.',
        icon: CheckCircle,
        cta: 'Learn More',
        color: 'text-amber-500',
        bgColor: 'bg-amber-50',
        premium: true,
      },
      {
        id: 'career-growth',
        title: 'Career Growth Membership',
        description: 'A monthly subscription that provides exclusive coaching resources and priority support services.',
        icon: BarChart3,
        cta: 'Join Now',
        color: 'text-amber-500',
        bgColor: 'bg-amber-50',
        premium: true,
      },
      {
        id: 'mentorship-program',
        title: 'Industry Mentorship Program',
        description: 'Connect with experienced mentors from top companies for guidance and industry insights.',
        icon: Award,
        cta: 'Find a Mentor',
        color: 'text-amber-500',
        bgColor: 'bg-amber-50',
        premium: true,
      },
      {
        id: 'referral-network',
        title: 'Job Referral Network',
        description: 'Gain access to our exclusive network of professionals who can refer you to opportunities at their companies.',
        icon: Users,
        cta: 'Join Network',
        color: 'text-amber-500',
        bgColor: 'bg-amber-50',
        premium: true,
      },
    ],
  },
];
