// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hidjuathfyiogrnxxxfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpZGp1YXRoZnlpb2dybnh4eGZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MzI3MzYsImV4cCI6MjA1ODEwODczNn0.0bFq676N_5KLkIxSK3GiburPezNuKi5aeld8EMkOHfQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);